In [1]:
import pandas as pd
from sklearn import linear_model
# import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('pakistan gdp.csv')
df.head(5)

date       GDP
0  12/31/1960   83.3379
1  12/31/1961   89.4090
2  12/31/1962   91.3192
3  12/31/1963   95.7034
4  12/31/1964  104.8802

In [3]:
# converting the date into year and dropping date column
df['year'] = pd. DatetimeIndex(df['date']). year
df1 = df.drop('date',axis = 1)
df1.head()

GDP  year
0   83.3379  1960
1   89.4090  1961
2   91.3192  1962
3   95.7034  1963
4  104.8802  1964

In [4]:
df1 = df1.astype(str)
df1.dtypes

GDP     object
year    object
dtype: object

In [5]:
# df1['year'] = df1['year'].astype(int)
# df1 = np.array(df1)

In [6]:
# # plotting the scatter plot
# %matplotlib inline
# plt.xlabel('Year')
# plt.ylabel('GDP')
# plt.scatter(df1.year,df1.GDP,color = 'red',marker = '+')

In [7]:
Year = df1.drop(['GDP'], axis = 1)
Year.head()

year
0  1960
1  1961
2  1962
3  1963
4  1964

In [8]:
Model = linear_model.LinearRegression()
Model.fit(Year,df1.GDP)

LinearRegression()

In [9]:
Model.predict([[2021]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1201.04364082])

In [10]:
Model.predict([[2022]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1222.72913732])

In [11]:
Model.predict([[2023]])

C:\Users\hp\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1244.41463383])

In [12]:
Model.score(Year,df1.GDP)

0.862219064040309

In [13]:
### Create a Pickle file using serialization 
import pickle
pickle_out = open("Model.pkl","wb")
pickle.dump(Model, pickle_out)
pickle_out.close()